### ISSUE TITLE
Not creating RamDisk on early startup before PageFile initialisation versions(2015 to 2022-08-26)

### ISSUE THREAD

**Issue by lazarusUser** [LTRData/ImDisk#16]
How do you do. 
Gratefully for your software and work. 

Need to create a RamDisk from image and place a PageFile on it.
But the RamDisk is being created after the Page File is requested.
This causes creation of temporary pagefile.sys

Windows 7
Task Scheduler running as SYSTEM on STARTUP:
start.cmd [imdisk -a -t vm -f "C:\ImD\X.img" -m X:]

Used tutorial from guru3D Forums of 2011, which worked for me under same conditions in the past.
with version ImDisk 2.0.6.

Tried also adding shortcut to folder "Startup" with the same parameters.

New versions seem to have "Run on system startup" - included in ImDisk Toolkit.
But this does not seem to work for me.

With respect.

**Comment by LTRData** [comment]
First of all, It is typically a very bad idea to try to put a page file on a VM type disk. They are backed by virtual memory that may get swapped out to disk, which could effectively mean that the page file might be stored in itself which will cause system hangs when data is swapped in to physical memory again.

If you really need a paging file in a RAM disk for some reason, at least drop `-t VM` and use `-o awe` instead. But I would also recommend that you check what happens if you instead run Windows without any page file at all (set to none in page file settings in Windows). In most cases that works perfectly and if it does not with some application, you could use my `swapadd` tool to create a paging file manually when system is running. You can even add swapadd to your script after the imdisk command to automatically create the paging file at that point to make sure that things happen in the correct order for it to work.

Swapadd tool is available here:
https://ltr-data.se/opencode.html

**Comment by lazarusUser** [comment]
Thank you for reply.
So what is about to be done: 
Imdisk_start.cmd:
`imdisk -a -o awe -s 10G -m Z: -p "/fs:ntfs /q /y"
swapadd Z:\pagefile.sys 1024M 1024M
`
And there are four options to run this file on startup:
Registry; \Startup; Task Scheduler; gpedit

Aside of all there is a question for me: why the built-in option "mount on startup" does not work?
Or I was doing something wrong?
I have seen that this problem was discussed on "reboot" in 2011. 
But may be there is a certain solution with the last versions of ImDisk?

Another question: As far it seems, that GUI and the driver are different. 
Is it possible to use the most pleasant (for me) GUI with the most efficient driver ( latest?, best working for me?)
And where to see the whole list of files added to system?

**Comment by LTRData** [comment]
The mount on startup command option `-p` should work, but it is a bit limited. It cannot format file systems for example, so you would need to have an image file pre-loaded with a file system that could be loaded into memory instead. But that takes some time and is typically not a recommended way to do this. Your script with `-o awe` followed by `swapadd` should be better in most cases.

Source code for the Control Panel applet is in this repository. It should be possible to open with latest Visual Studio versions, but you might need to install several additional components like WDK and similar because the solution also contains driver projects.

If you are on the other hand referring to ImDisk Toolkit, that is a different thing and is not included here and not developed by me. It is developed by "v77" and is available in a SourceForge repository:
https://sourceforge.net/projects/imdisk-toolkit/

**Comment by lazarusUser** [comment]
So far understand it so (trying to figure out a manual):
1. install ImDisk
2. copy swapadd and rawcopy to Windows\system32
3. prepare an image file in... C:\images\Z.img  //formatted NTFS  with command: 
`imdisk -a -o awe -s 5G -m Z: -p "/fs:ntfs /q /y"`
Then
`rawcopy -mld \\.\Z: "C:\images\Z.img"`
- thus getting an image formatted to NTFS
4. prepare a Start.cmd:
`imdisk -a -o awe -f "C:\images\Z.img" -m Z:`
`swapadd Z:\pagefile.sys 1024M 1024M`
5. put Start.cmd to startup by means of any approach or try with ImDiskToolkit...
If you suggest no corrections - will keep this as a manual.
Thank you in advance.

**Comment by LTRData** [comment]
Yes, it gets a bit unnecessarily complicated in the beginning though. You could just mount the image file directly, format it and dismount it. You do not need rawcopy for that.

Instead of #3, you could do this:

`imdisk -a -f "C:\images\Z.img" -o sparse -s 5G -m Z: -p "/fs:ntfs /q /y"`
Followed by
`imdisk -d -m Z:`

That will save a lot of time.
