### ISSUE TITLE
Some executables are not able to call Windows APIs correctly when put inside the ramdisk

### ISSUE THREAD

**Issue by FlyMan2004** [LTRData/ImDisk#21]
### SYSTEM INFORMATION
| ITEM | VALUE |
| - | - |
| OS Name | Microsoft Windows 11 Pro for Workstations |
| Version | 10.0.26100 Build 26100.994 |
| System Type | x64-based PC |
| Installed Physical Memory (RAM) |	64.0 GB |
| Total Physical Memory |	63.2 GB |
| Available Physical Memory |	46.7 GB |
| Total Virtual Memory |	76.2 GB |
| Available Virtual Memory |	56.5 GB |
| Page File Space | 	13.0 GB |
### PROBLEM DETAILS
Many installer exe file like 7-zip installer cannot be executed within the ramdisk. This happens on a newly installed system since 24H2 update. However, most of executables will not complain, such as 7zr.exe and a simple c++-written hello world.
![Screenshot 2024-06-25 181820](https://github.com/LTRData/ImDisk/assets/44521347/8df704fd-730e-48e9-bb52-760106231eea)
![Screenshot 2024-06-25 181811](https://github.com/LTRData/ImDisk/assets/44521347/375ff2d0-f9dc-4b74-a16d-820d00745fc6)
![Screenshot 2024-06-25 181643](https://github.com/LTRData/ImDisk/assets/44521347/1b38b541-e4d6-4167-a52c-8a939679fc5c)
![Screenshot 2024-06-25 181622](https://github.com/LTRData/ImDisk/assets/44521347/3cc58a8b-883e-4b2c-aeac-6b192b06147f)

![Screenshot 2024-06-25 224859](https://github.com/LTRData/ImDisk/assets/44521347/d8d70f9f-1040-4c97-a57f-ed558faa03f3)

**Comment by LTRData** [comment]
Thanks for your report.

ImDisk is based on a very old driver design and there are several compatibility issues on modern versions of Windows. Development was practically stopped many years ago and I have since focused on Arsenal Image Mounter and some other related projects instead, which do not have the same kind of issues due to a fundamentally different driver design.

Please also note that this repository is about ImDisk Virtual Disk Driver, that is the driver, Control Panel applet and related API. You are using ImDisk Toolkit on top of it, which is maintained in this repository: https://sourceforge.net/projects/imdisk-toolkit/

**Comment by oood** [comment]
I made a small mitigation for this. 

https://github.com/oood/Win11-RAMDisk-Admin-Fix

Alternatively you can run your executable in an elevated command prompt and it will not cause an error.
