### ISSUE TITLE
The build date and download size on https://ltr-data.se/opencode.html have changed, but the version number has not

### ISSUE THREAD

**Issue by Gitoffthelawn** [LTRData/ImDisk#3]
Hi Olof,

I downloaded https://ltr-data.se/files/imdiskinst.exe from https://ltr-data.se/opencode.html/ (that's your site, correct?) the other day, and the site indicated it was v2.1.1, built on 2021-11-05 (IIRC).  The download was 613KB.

I then returned to https://ltr-data.se/opencode.html/ a few hours ago, and it indicated the version number was still v2.1.1, but it now indicated it was built on 2021-11-07 (as opposed to 2021-11-05).  The download size increased substantially to 641KB.

Also, 4 security vendors currently flag this file as malicious on virustotal.com, whereas the release from a couple days ago only currently has 1 malware flag.

Do you know what's going on?

Why is the download from https://ltr-data.se/opencode.html/ changing without the version number changing?

Also, why do none of the file timestamps match the build date?

Thank you for your help.

**Comment by LTRData** [comment]
It is the same version. If I recompile anything, I change the version number. This was just a fix for the setup package itself, there were no changes to files within it. I saw no reason to change version number, recompile everything, go though the process of sending it to Microsoft for signing etc in this case, because nothing needed to change.

The "build date" is the timestamp of the setup package.

**Comment by LTRData** [comment]
It is always the case with new releaes of ImDisk that they are flagged as malicious for a while until antimalware vendors have got requests for analysis and white listed them. If it is mostly the installer itself that triggers, there could be differences between this one and the installer that I mistakenly shipped a few days ago that did not work.
